### ISSUE TITLE
Get basic statistics on grants at different sizes and the categories used in the survey. 

### ISSUE THREAD

**Issue by selina-aragon** [softwaresaved/esrc-software-study#22] opened 2021-12-20 14:49 UTC
Action on Mario. In progress - update from 16 Dec 2021.

**Comment by marioa** [comment] 2022-01-05 09:54
Categories used in the survey are:

1. Area Studies
1. Demography
1. Development studies
1. Economics
1. Education
1. Environmental planning
1. History
1. Human Geography
1. Law & legal studies
1. Linguistics
1. Management & business studies
1. Political science. & international studies
1. Psychology
1. Science and Technology Studies
1. Social anthropology
1. Social policy
1. Social work
1. Sociology
1. Tools, technologies & methods

and there is the general catch-all:

* Other

These come from a breakdown used in the [ESRC application and success rate data and analysis](https://www.ukri.org/publications/esrc-application-and-success-rate-data-and-analysis/) in their breakdown of expenditure by discipline. This does not match the GtR breakdown in subjects and topics.

**Comment by marioa** [comment] 2022-01-06 11:30
Mapped GtR subjects to categories according to:

* Area Studies: Area Studies
* Demography: Demography, Demography & human geography
* Development studies: Development studies
* Economics: Economics
* Education: Education
* Environmental planning: Environmental planning
* History: History
* Human Geography: Human Geography
* Law & legal studies: Law & legal studies
* Linguistics: Linguistics, Languages & Literature
* Management & business studies: Management & Business Studies
* Political science. & international studies: Pol. sci. & internat. studies
* Psychology: Psychology
* Science and Technology Studies: Science and Technology Studies
* Social anthropology: Social Anthropology
* Social policy: Social Policy
* Social work: Social Work
* Sociology: Sociology
* Tools, technologies & methods: "Tools, technologies & methods"
* Other: RCUK Programmes, Genetics & development, Climate & Climate Change,
       Media, "Ecol, biodivers. & systematics", Civil eng. & built environment,
       Info. & commun. Technol., Medical & health interface,
       Visual arts, Design, Complexity Science, "Pollution, waste & resources",
       Terrest. & freshwater environ., Agri-environmental science,
       Food science & nutrition, Environmental Engineering,
       Manufacturing, Drama & theatre studies, Cultural & museum studies,
       Philosophy, Animal Science, Energy, Mathematical sciences, Archaeology,
       Music, "Theology, divinity & religion", Library & information studies,
       Astronomy - observation, Astronomy - theory,
       Particle Astrophysics, Bioengineering, Cell biology, Process engineering,
       Omic sciences & technologies, Systems engineering, Marine environments,
       Atmospheric phys. & chemistry, Plant & crop science, Electrical Engineering,
       Dance, Chemical measurement, Geosciences, Microbial sciences,
       Mechanical Engineering, Classics, Catalysis & surfaces, Materials sciences,
       Instrument. sensor & detectors, Materials Processing
* Uncategorised: NA

For all projects, this gives a breakdown of the number of awards and amount awarded as:

|Category                                   |Number of awards |Award (£)     |
|:------------------------------------------|:----------------|:-------------|
|Other                                      |1,720            |1,309,234,143 |
|Economics                                  |1,205            |977,428,081   |
|Sociology                                  |2,120            |973,573,071   |
|Uncategorised                              |4,200            |669,095,758   |
|Psychology                                 |1,563            |576,619,954   |
|Social policy                              |1,144            |561,063,960   |
|Demography                                 |736              |430,479,646   |
|Development studies                        |900              |402,851,786   |
|Education                                  |835              |402,210,888   |
|Human Geography                            |593              |390,230,574   |
|Tools, technologies & methods              |605              |386,282,277   |
|Political science. & international studies |1,164            |358,095,877   |
|Management & business studies              |788              |330,816,871   |
|Social anthropology                        |494              |170,802,980   |
|Law & legal studies                        |474              |148,830,877   |
|Linguistics                                |394              |119,954,626   |
|History                                    |318              |114,823,355   |
|Environmental planning                     |273              |101,139,857   |
|Social work                                |212              |86,945,821    |
|Science and Technology Studies             |152              |61,595,683    |
|Area Studies                               |129              |48,469,980    |

The `Other` category dominates. Looking at the `Other` category in more detail:

|Subject                        |Number of awards |Award (£)   |
|:------------------------------|:----------------|:-----------|
|RCUK Programmes                |376              |327,072,642 |
|Medical & health interface     |296              |313,307,633 |
|Genetics & development         |31               |95,931,632  |
|Info. & commun. Technol.       |143              |89,426,259  |
|Civil eng. & built environment |80               |50,878,362  |
|Climate & Climate Change       |63               |47,109,029  |
|Visual arts                    |56               |35,161,484  |
|Mathematical sciences          |41               |33,321,846  |
|Design                         |59               |30,522,406  |
|Agri-environmental science     |45               |29,990,577  |
|Complexity Science             |35               |24,456,399  |
|Library & information studies  |8                |24,365,609  |
|Media                          |82               |24,324,123  |
|Energy                         |39               |22,011,030  |
|Ecol, biodivers. & systematics |25               |19,386,080  |
|Animal Science                 |47               |17,671,897  |
|Food science & nutrition       |43               |16,667,374  |
|Philosophy                     |46               |14,391,571  |
|Theology, divinity & religion  |19               |12,174,365  |
|Pollution, waste & resources   |17               |10,958,985  |
|Cultural & museum studies      |45               |9,677,686   |
|Environmental Engineering      |8                |9,585,824   |
|Terrest. & freshwater environ. |11               |9,306,244   |
|Mechanical Engineering         |4                |6,121,077   |
|Microbial sciences             |7                |5,341,318   |
|Drama & theatre studies        |13               |4,189,840   |
|Omic sciences & technologies   |5                |2,984,565   |
|Manufacturing                  |12               |2,681,523   |
|Atmospheric phys. & chemistry  |2                |2,485,475   |
|Systems engineering            |4                |2,447,945   |
|Bioengineering                 |3                |2,349,845   |
|Geosciences                    |10               |2,303,237   |
|Music                          |10               |1,922,717   |
|Electrical Engineering         |8                |1,799,765   |
|Marine environments            |4                |1,534,490   |
|Cell biology                   |3                |1,103,904   |
|Plant & crop science           |1                |876,346     |
|Archaeology                    |5                |755,745     |
|Materials Processing           |1                |614,537     |
|Classics                       |1                |604,605     |
|Dance                          |2                |304,808     |
|Materials sciences             |3                |286,101     |
|Process engineering            |3                |244,452     |
|Astronomy - observation        |1                |154,236     |
|Astronomy - theory             |1                |154,236     |
|Particle Astrophysics          |1                |154,236     |
|Catalysis & surfaces           |1                |120,083     |

There are some rather large awards at the top. 

Only looking at active projects:

|Category                                   |Number of awards |Award (£)   |
|:------------------------------------------|:----------------|:-----------|
|Other                                      |693              |930,538,696 |
|Uncategorised                              |3,480            |525,669,962 |
|Economics                                  |233              |460,369,620 |
|Sociology                                  |409              |388,269,450 |
|Social policy                              |233              |280,841,039 |
|Human Geography                            |246              |263,433,315 |
|Development studies                        |193              |218,904,193 |
|Psychology                                 |307              |192,422,408 |
|Demography                                 |49               |185,308,260 |
|Education                                  |163              |160,058,416 |
|Management & business studies              |144              |142,451,796 |
|Political science. & international studies |193              |120,737,876 |
|Tools, technologies & methods              |70               |105,021,249 |
|Law & legal studies                        |95               |66,171,046  |
|Social anthropology                        |102              |62,749,981  |
|Social work                                |47               |45,960,023  |
|Environmental planning                     |50               |43,212,649  |
|Science and Technology Studies             |66               |38,907,035  |
|Area Studies                               |60               |33,095,666  |
|Linguistics                                |61               |26,028,868  |
|History                                    |47               |19,738,089  |

Now the projects that do not have a subject associated with them come more to the fore. Looking at the `Other` category in more detail for only active projects.

|Subject                        |Number of awards |Award (£)   |
|:------------------------------|:----------------|:-----------|
|RCUK Programmes                |139              |284,394,917 |
|Medical & health interface     |124              |212,894,423 |
|Genetics & development         |4                |61,270,745  |
|Info. & commun. Technol.       |65               |48,791,910  |
|Civil eng. & built environment |33               |37,605,408  |
|Climate & Climate Change       |25               |33,386,120  |
|Visual arts                    |32               |30,473,965  |
|Library & information studies  |1                |21,847,174  |
|Agri-environmental science     |17               |20,963,719  |
|Design                         |27               |20,055,994  |
|Mathematical sciences          |13               |19,648,064  |
|Energy                         |17               |17,387,671  |
|Media                          |30               |14,457,597  |
|Ecol, biodivers. & systematics |10               |14,224,739  |
|Pollution, waste & resources   |9                |9,540,993   |
|Environmental Engineering      |6                |9,534,670   |
|Theology, divinity & religion  |5                |8,909,886   |
|Complexity Science             |16               |8,768,043   |
|Food science & nutrition       |19               |7,990,182   |
|Terrest. & freshwater environ. |5                |7,690,792   |
|Animal Science                 |14               |7,293,905   |
|Philosophy                     |14               |4,598,585   |
|Cultural & museum studies      |15               |4,107,551   |
|Drama & theatre studies        |8                |3,471,565   |
|Microbial sciences             |2                |2,874,555   |
|Atmospheric phys. & chemistry  |2                |2,485,475   |
|Bioengineering                 |2                |2,271,473   |
|Systems engineering            |3                |2,181,855   |
|Electrical Engineering         |7                |1,772,626   |
|Geosciences                    |4                |1,647,627   |
|Marine environments            |3                |1,382,052   |
|Music                          |4                |1,255,555   |
|Manufacturing                  |5                |1,228,365   |
|Cell biology                   |3                |1,103,904   |
|Plant & crop science           |1                |876,346     |
|Materials Processing           |1                |614,537     |
|Classics                       |1                |604,605     |
|Omic sciences & technologies   |2                |430,295     |
|Mechanical Engineering         |3                |395,522     |
|Process engineering            |1                |95,408      |
|Archaeology                    |1                |9,878       |

**Comment by marioa** [comment] 2022-01-06 15:42
For now, ignore `Other` and `Uncategorised` and work out the percentage representation for each category in terms of: 
- [ ] award and 
- [ ] number of awards

**Comment by marioa** [comment] 2022-01-12 13:55
The previous numbers are overcounting - more than one subject can be assigned to a project. Can create a fraction contribution for each subject. So, if a project has n subjects then each will contribute 1/n to that subject. In the process of working this out identified another problem with the data - the grant reference was not unique. The original data seems to be fine so it must have got corrupted on download. Trying to download the data from scratch to see if this fixes the problem. The code seems fine so I don't think the problem is there.

**Comment by marioa** [comment] 2022-01-14 13:32
Removing:
*  `Uncategorised` projects (where there is no subject classification for a project)
*  `Other`s where there is no straightforward mapping between a subject and a category

and taking into account fractional contribution (where multiple subjects, say n, then each will contribute 1/n to the category if it can be mapped and the award will be distributed by Award/n) we then get:

|Category                                   |Number of awards |Number % |Award (£)   |Award % |
|:------------------------------------------|:----------------|:--------|:-----------|:-------|
|Uncategorised                              |3,499.0          |70       |524,231,858 |30      |
|Other                                      |225.3            |5        |265,753,172 |15      |
|Economics                                  |124.3            |3        |149,327,425 |9       |
|Social policy                              |102.4            |2        |116,707,405 |7       |
|Sociology                                  |170.7            |3        |111,993,415 |6       |
|Psychology                                 |178.0            |4        |84,534,261  |5       |
|Human Geography                            |96.5             |2        |77,531,039  |4       |
|Development studies                        |69.4             |1        |63,823,495  |4       |
|Education                                  |81.9             |2        |60,149,023  |3       |
|Political science. & international studies |100.4            |2        |49,913,001  |3       |
|Management & business studies              |66.9             |1        |49,858,340  |3       |
|Demography                                 |17.8             |0        |48,343,804  |3       |
|Tools, technologies & methods              |26.1             |1        |29,496,702  |2       |
|Law & legal studies                        |45.2             |1        |22,429,396  |1       |
|Social work                                |20.0             |0        |16,681,853  |1       |
|Social anthropology                        |40.0             |1        |16,437,605  |1       |
|Science and Technology Studies             |25.1             |1        |13,142,325  |1       |
|Environmental planning                     |16.7             |0        |11,459,591  |1       |
|Linguistics                                |28.4             |1        |10,401,719  |1       |
|Area Studies                               |18.7             |0        |8,518,577   |0       |
|History                                    |18.7             |0        |6,384,249   |0       |

We can generate a pie chart for the proportion by the award amount

![image](https://user-images.githubusercontent.com/551992/149523229-2fa5dcfe-a2c5-45aa-8d34-e360e62bed8e.png)

or by the number of awards (by adding all the factional contributions):

![image](https://user-images.githubusercontent.com/551992/149523351-e1b39a50-efc1-4510-b89e-724d61c17c3b.png)

**Closed by marioa** 2022-01-14 13:32 UTC
Labels: desk research
